-- StubsGenTests lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'
require 'functional'

return function(obj)
    obj['testLuaNullable'] = wrap(obj['testLuaNullable'], function(origFunc)
        return function(...)
            local a, b = checkargsEx(
                {level=1},
                {
                    {type = 'int', nullable = true},
                    {type = 'string'},
                },
                ...
            )
            local _rets = {origFunc(a, b)}
            return table.unpack(_rets)
        end
    end)

    obj['testLuaDefault'] = wrap(obj['testLuaDefault'], function(origFunc)
        return function(...)
            local a, b = checkargsEx(
                {level=1},
                {
                    {type = 'int'},
                    {type = 'string', default = "x"},
                },
                ...
            )
            local _rets = {origFunc(a, b)}
            return table.unpack(_rets)
        end
    end)

end
